CREATE TABLE ENDERECO
(
 RUA VARCHAR2(200) NOT NULL
,NUMERO NUMBER NOT NULL
, COMPLEMTO VARCHAR2(4)NOT NULL
,ID_ENDERECO NUMBER NOT NULL
,CONSTRAINT ENDERECO_PK PRIMARY KEY (ID_ENDERECO) ENABLE
);

CREATE TABLE CONTA
(
 NUMERO NUMBER NOT NULL
,SALDO NUMBER NOT NULL
,LIMITE NUMBER NOT NULL
,CONSTRAINT CONTA_PK PRIMARY KEY (NUMERO) ENABLE
);

CREATE TABLE PESSOA
(
 NOME VARCHAR2(200) NOT NULL
,IDADE NUMBER NOT NULL
,SEXO VARCHAR2(2) NOT NULL
,CPF VARCHAR2(11) NOT NULL
,ID_ENDERECO NUMBER NULL
,NUMERO_CONTA NUMBER NULL
,CONSTRAINT PESSOA_PK PRIMARY KEY (CPF) ENABLE
);

/*CRIAÇÃO DE CHAVE ESTRANGEIRA LIGANDO A TABELA PESSOA A ENDEREÇO E CONTA*/
ALTER TABLE PESSOA ADD CONSTRAINT FK_ID_ENDERECO foreign key( ID_ENDERECO ) references ENDERECO(ID_ENDERECO);
ALTER TABLE PESSOA ADD CONSTRAINT FK_NUMERO_CONTA foreign key( NUMERO_CONTA ) references CONTA(NUMERO);

/*CRIANDO SEQUENCE*/
CREATE SEQUENCE S_ID_ENDERECO INCREMENT BY 1 START WITH 1 MINVALUE 1;